Visionplus/Visionplus/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('visionplusapp.urls', namespace='visionplusapp')),
]

Visionplus/visionplusapp/urls.py
from django.urls import path
from .views import edit, dashboard, register, showvideo
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)
from django.conf import settings
from django.conf.urls.static import static

app_name = 'visionplusapp'

urlpatterns = [
    path('register/', register, name='register'),
    path('dashboard/video', showvideo, name='showvideo'),
    path('edit/', edit, name='edit'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='visionplusapp/logged_out.html'), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='visionplusapp/password_change_form.html'), name='password_change'),
    path('password_change/dond/', PasswordChangeDoneView.as_view(template_name='visionplusapp/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='visionplusapp/password_reset_form.html',
        email_template_name='visionplusapp/password_reset_email.html',
        success_url=reverse_lazy('visionplusapp:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='visionplusapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='visionplusapp/password_reset_confirm.html',
        success_url=reverse_lazy('visionplusapp:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='visionplusapp/password_reset_complete.html'), name='password_reset_complete'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Visionplus/visionplusapp/models.py
from django.db import models
from django.conf import settings


class UserRegistrationModel(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class Analysis(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT
    )
    score = models.CharField(max_length=500)


class ImageModel(models.Model):
    img = models.ImageField(upload_to=user_directory_path, null = True)
    name = models.CharField(max_length=500)
    analysis = models.ForeignKey(Analysis, on_delete=models.PROTECT, null=True)

Visionplus/visionplusapp/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import Analysis




class UserRegistration(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class AnalysisForm(forms.ModelForm):
    class Meta:
        model= Analysis
        fields= ['user', 'score']

Visionplus/visionplusapp/views.py
from django.http import request
from django.shortcuts import render
from .models import ImageModel,Analysis
from django.contrib.auth.decorators import login_required
from .forms import UserRegistration, UserEditForm, AnalysisForm
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.core.files.base import ContentFile
from .service import  grade
from django.core.paginator import Paginator

from PIL import Image
import io
import base64

import sklearn
import pickle


import cv2

# Create your views here.

@login_required
def dashboard(request):
    context = {
        "welcome": "Welcome to your dashboard"
    }
    return render(request, 'visionplusapp/dashboard.html', context=context)


def register(request):
    if request.method == 'POST':
        form = UserRegistration(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            return render(request, 'visionplusapp/register_done.html')
    else:
        form = UserRegistration()

    context = {
        "form": form
    }

    return render(request, 'visionplusapp/register.html', context=context)


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        print("here")
        print(user_form)
    context = {
        'form': user_form,
    }
    return render(request, 'visionplusapp/edit.html', context=context)

@csrf_exempt
def showvideo(request):
    request.upload_handlers.pop(0)
    return showvideo(request)

@login_required
def showvideo(request):
    with open('D:/majorProject/Vision+/R&D_POC/major/body_language.pkl', 'rb') as f:
        model = pickle.load(f)
    with open('D:/majorProject/Vision+/R&D_POC/major/face_recog.pkl', 'rb') as f1:
        facemodel = pickle.load(f1)
    user = request.user
    print(request.FILES)
    video_obj = request.FILES.get('videofile', False)
    vid_path = video_obj.temporary_file_path()
    initial,score, imgs = grade(vid_path,model,facemodel)
    # print("stage 1")
    # score, imgs = gradeHands(vid_path,score,imgs,model)
    # print("stage 2")
    # score, imgs = gradeExp(vid_path, score, imgs,facemodel)
    # print("stage 3")
    print(score)
    print(initial)
    normalized_score =round( (score / initial) *100,2)
    response =[]
    print(normalized_score)
    #print(imgs)
    for i in imgs:
        pillow_image = Image.fromarray(i)
        buffer = io.BytesIO()
        pillow_image.save(buffer, format='JPEG')
        img_str = base64.b64encode(buffer.getvalue()).decode()
        response.append("data:image/jpeg;base64,"+img_str)


    context = {'videofile': "abc",
               'form': "form",
               'score':normalized_score,
               'images': response
               }

    return render(request, 'visionplusapp/dashboard.html', context)

Visionplus/visionplusapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <style>
   section{
  margin-top: 40px;
}
.card {
  border: 2px solid red;
  margin: 10px 4px;
  transition: .6s ease;
}

.card:hover {
  transform: scale(1.05);
}

.card-block {
   padding: 10px;
}

.scrollcards {
  background-color: #fff;
  overflow: auto;
  white-space: nowrap;
}

::-webkit-scrollbar {
    width: 0px;
    height: 0px;
    background: transparent;
}

div.scrollcards .card {
    display: inline-block;
    padding: 14px;
    text-decoration: none;
    height: auto;
    width: 300px;
}

.file-upload-form {
  max-width: 500px;
  margin: 0 auto;
}

.custom-file-upload {
  display: inline-block;
  padding: 10px 20px;
  cursor: pointer;
  border: none;
  border-radius: 5px;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.2);
  text-align: center;
}

.custom-file-upload:hover {
  background-color: #0069d9;
}

.form-control-file {
  opacity: 0;
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  cursor: pointer;
}


    </style>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    


<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />

<!-- Nucleo Icons -->
<link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
<link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />

<!-- Font Awesome Icons -->
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>

<!-- Material Icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

<!-- CSS Files -->



<link id="pagestyle" href="{% static 'css/material-dashboard.css'%}" rel="stylesheet" />




    <title>Vision+ {% block title %}{% endblock title %}</title>
</head>

  <body class="g-sidenav-show  bg-gray-100">


 {% block content %}

        {% endblock content %}







    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>


<!--   Core JS Files   -->
<script src="{% static 'js/core/popper.min.js'%}" ></script>
<script src="{% static 'js/core/bootstrap.min.js'%}" ></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js'%}" ></script>
<script src="{% static 'js/plugins/smooth-scrollbar.min.js'%}" ></script>
 <script src="{% static 'js/plugins/chartjs.min.js'%}" ></script>


<script>
  var win = navigator.platform.indexOf('Win') > -1;
  if (win && document.querySelector('#sidenav-scrollbar')) {
    var options = {
      damping: '0.5'
    }
    Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
  }
</script>

 <script>

    var ctx2 = document.getElementById("chart-line").getContext("2d");

    new Chart(ctx2, {
      type: "line",
      data: {
        labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        datasets: [{
          label: "Mobile apps",
          tension: 0,
          borderWidth: 0,
          pointRadius: 5,
          pointBackgroundColor: "rgba(255, 255, 255, .8)",
          pointBorderColor: "transparent",
          borderColor: "rgba(255, 255, 255, .8)",
          borderColor: "rgba(255, 255, 255, .8)",
          borderWidth: 4,
          backgroundColor: "transparent",
          fill: true,
          data: [50, 40, 300, 320, 500, 350, 200, 230, 500],
          maxBarThickness: 6

        }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: false,
          }
        },
        interaction: {
          intersect: false,
          mode: 'index',
        },
        scales: {
          y: {
            grid: {
              drawBorder: false,
              display: true,
              drawOnChartArea: true,
              drawTicks: false,
              borderDash: [5, 5],
              color: 'rgba(255, 255, 255, .2)'
            },
            ticks: {
              display: true,
              color: '#f8f9fa',
              padding: 10,
              font: {
                size: 14,
                weight: 300,
                family: "Roboto",
                style: 'normal',
                lineHeight: 2
              },
            }
          },
          x: {
            grid: {
              drawBorder: false,
              display: false,
              drawOnChartArea: false,
              drawTicks: false,
              borderDash: [5, 5]
            },
            ticks: {
              display: true,
              color: '#f8f9fa',
              padding: 10,
              font: {
                size: 14,
                weight: 300,
                family: "Roboto",
                style: 'normal',
                lineHeight: 2
              },
            }
          },
        },
      },
    });


  </script>
  <script>

</script>

  </script>

    
</body>

</html>

Visionplus/visionplusapp/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}
{% block content %}

{% endblock content %}

Visionplus/visionplusapp/templates/navbar.html
{% load static %}
{% if request.user.is_authenticated %}

<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href="#" target="_blank">
        <img src="{% static 'img/logo-ct.png'%}" class="navbar-brand-img h-100" alt="main_logo">
        <span class="ms-1 font-weight-bold text-white">Vision+</span>
      </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'visionplusapp:dashboard' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">dashboard</i>
            </div>
            <span class="nav-link-text ms-1">Dashboard</span>
          </a>
        </li>

        <li class="nav-item mt-3">
          <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Account pages</h6>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'visionplusapp:edit' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">person</i>
            </div>
            <span class="nav-link-text ms-1">Profile</span>
          </a>
        </li>

      </ul>
    </div>

  </aside>

{% endif %}
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <h6 class="font-weight-bolder mb-0">Vision+</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">

          </div>
          <ul class="navbar-nav  justify-content-end">
            <li class="nav-item d-flex align-items-center">
              {% if request.user.is_authenticated %}
              <a href="{% url 'visionplusapp:logout' %}" class="nav-link text-body font-weight-bold px-0">
                <i class="fa fa-user me-sm-1"></i>
                <span class="d-sm-inline d-none">Sign out</span>
              </a>
              {% else %}
                <a href="{% url 'visionplusapp:login' %}" class="nav-link text-body font-weight-bold px-0">
                <i class="fa fa-user me-sm-1"></i>
                <span class="d-sm-inline d-none">Sign In</span>
              </a>
              {% endif %}
            </li>


          </ul>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->

  </main>

Visionplus/visionplusapp/templates/visionplusapp/dashboard.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Dashboard{% endblock title %}
{% block content %}




 <main class="main-content  mt-0">
    <div class="page-header align-items-start min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container my-auto">
        <div class="row">
          {% if page %}
          <div class=" row justify-content-start">
          <div class="col-lg-4 col-md-4 col-4 ">
        {% else %}
               <div class=" row justify-content-center">
              <div class="col-lg-4 col-md-4 col-4 text-center">
               {% endif %}
            <div class="card z-index-0 fadeIn3 fadeInBottom">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                  <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Upload Video</h4>

                </div>
              </div>

              <div class="card-body">
                <form role="form" action="video" method="post"  enctype="multipart/form-data" class="text-start">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="hidden" name="name"  maxlength="150" class="form-control" placeholder="File Name" id="id_filename">

                        <div class=" input-group-outline my-4 mb-2 text-center">
    <label for="id_videofile" class="custom-file-upload ">
      <i class="fas fa-cloud-upload-alt "></i> Choose file
    </label>

    <input type="file" id="id_videofile" name="videofile" class=" form-control form-control-file" required>
                             </div>
  </div>
                     <div class="text-center">
  <button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">Upload</button>
                  </div>
                </form>
              </div>
            </div>
              {% if score %}

               <h4>Score : {{ score }}</h4>
              {% endif %}
          </div>
              {% if images %}
            <div class="col-lg-8 col-md-8 col-8">
<section>
  <div class="container-fluid">
    <div class="row">

      <div class="scrollcards">
    {% for image in images %}
          <div class="card">
            <img class="card-img-top" src="{{ image }}">
          </div>
           {% endfor %}
               </div>

    </div>
   </div>
</section>
            </div>
            {% endif %}
        </div>
      </div>
            </div>
          </div>




        </div>
      </div>
      <footer class="footer position-absolute bottom-2 py-2 w-100">
        <div class="container">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-12 col-md-6 my-auto">


        </div>
      </footer>
    </div>
  </main>
{% endblock content %}

Visionplus/visionplusapp/templates/visionplusapp/edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Edit{% endblock title %}
{% block content %}
<h2>Edit your account</h2>
<p>You can edit your account using the follow form</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

Visionplus/visionplusapp/templates/visionplusapp/logged_out.html
{% extends "base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
<h1>Logged out</h1>
<p>
    You have been successfully logged out.
    <hr>
    You can <a href="{% url 'visionplusapp:login' %}">log-in again</a>.
</p>
{% endblock %}

Visionplus/visionplusapp/templates/visionplusapp/password_change_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<h2>Change Your Password</h2>
<p>Use the form below to change your Password</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

Visionplus/visionplusapp/templates/visionplusapp/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}
<h2>Password set</h2>
<p>Your password has been set. You can
    <a href="{% url 'authapp:login' %}">log in now</a></p>
{% endblock %}

Visionplus/visionplusapp/templates/visionplusapp/password_reset_confirm.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
{% if validlink %}
<p>Please enter your new password twice:</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" value="Change my password">Submit</button>
    {% endbuttons %}
</form>
{% else %}
<p>The password reset link was invalid, possibly because it has
    already been used. Please request a new password reset.</p>
{% endif %}
{% endblock %}

Visionplus/visionplusapp/templates/visionplusapp/password_reset_done.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
<p>We've emailed you instructions for setting your password.</p>
<p>If you don't receive an email, please make sure you've entered
    the address you registered with.</p>
{% endblock %}

Visionplus/visionplusapp/templates/visionplusapp/password_reset_email.html
Someone asked for password reset for email {{email}}.Follow the Link below
{{ protocol }}://{{ domain }}{% url "authapp:password_reset_confirm"
uidb64=uid token=token %}

Visionplus/visionplusapp/templates/visionplusapp/password_reset_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Reset your password

{% endblock title %}
{% block content %}
<div class="container">
    <h2>Forgotten your Password</h2>
    <p>Enter your email address to obtain a new password</p>
    <form action="" method="post" class="form ">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary" value="send e-mail">Submit</button>
        {% endbuttons %}
    </form>
</div>
{% endblock content %}

Visionplus/visionplusapp/templates/visionplusapp/register.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Registration

{% endblock title %}
{% block content %}

{% if form.errors %}
    
{% endif %}
<!--    <form action="" method="post" class="form container">-->
<!--    {% csrf_token %}-->
<!--    {% bootstrap_form form %}-->
<!--    {% buttons %}-->
<!--    <button type="submit" class="btn btn-primary">Submit</button>-->
<!--    {% endbuttons %}-->
<!--</form>-->

  <main class="main-content  mt-0">
    <section>
      <div class="page-header min-vh-100">
        <div class="container">
          <div class="row">
            <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 start-0 text-center justify-content-center flex-column">
              <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center" style="background-image: url('{% static 'img/illustrations/illustration-signup.jpg' %}'); background-size: cover;">
              </div>
            </div>
            <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-5">
              <div class="card card-plain">
                <div class="card-header">
                  <h4 class="font-weight-bolder">Sign Up</h4>
                  <p class="mb-0">Enter your email and password to register</p>
                </div>
                <div class="card-body">
                  <form action="" method="post" role="form">
				   {% csrf_token %}
                       <div class="input-group input-group-outline mb-3">

<input type="text" name="username" maxlength="150" class="form-control" placeholder="Username" title="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only." required="" id="id_username">
                    </div>
                    <div class="input-group input-group-outline mb-3">

                     <input type="text" name="first_name" maxlength="150" class="form-control" placeholder="First name" title="" id="id_first_name">
                    </div>
				 <div class="input-group input-group-outline mb-3">

				 <input type="text" name="last_name" maxlength="150" class="form-control" placeholder="Last name" title="" id="id_last_name">
				 </div>
                    <div class="input-group input-group-outline mb-3">

                      <input type="email" name="email" maxlength="254" class="form-control" placeholder="Email address" title="" id="id_email">
                    </div>
                    <div class="input-group input-group-outline mb-3">

                     <input type="password" name="password" class="form-control" placeholder="Password" title="" required="" id="id_password">
                    </div>
				 <div class="input-group input-group-outline mb-3">

				 <input type="password" name="password2" class="form-control" placeholder="Repeat Password" title="" required="" id="id_password2">
				 </div>

                    <div class="text-center">
                      <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Sign Up</button>
                    </div>
                  </form>
                </div>
                <div class="card-footer text-center pt-0 px-lg-2 px-1">
                  <p class="mb-2 text-sm mx-auto">
                    Already have an account?
                    <a href="{% url 'visionplusapp:login' %}"  class="text-primary text-gradient font-weight-bold">Sign in</a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>



 </main>


{% endblock content %}

Visionplus/visionplusapp/templates/visionplusapp/register_done.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome {{ new_user.first_name }}!</h1>
<p>Your account has been successfully created. Now you can <a href="{% url 'visionplusapp:login' %}">log in</a>.</p>
{% endblock content %}